### ISSUE TITLE
Some games seem invisible to APIs.

### ISSUE THREAD

**Issue by jdaymude** [jdaymude/xbox2local#9]
**Description**
The xbox2local script appears to be performing correctly for most all games, but there are some that are not surfaced by X API. In particular, I've experienced this with Sea of Thieves, though there may be other titles as well. However, those screenshots and game clips are definitely uploaded to Xbox Live and are visible on first- and third-party services like the Xbox iOS app, GameDVR, etc. This seems to be upstream (X API) since even the direct `curl` calls do not surface any metadata, however.

**To Reproduce**
1. Take game media in a problematic game, like Sea of Thieves.
2. Ensure that those game media are uploaded to Xbox Live.
3. Run xbox2local and observe that the media is not downloaded.

**Expected Behavior**
All game media should be downloaded.

**Comment by jdaymude** [comment]
As of August 30, 2021, the "invisible" games in my library are:
- Control Ultimate Edition - Xbox Series X|S
- Gears Tactics - Base Game
- Minecraft
- Sea of Thieves
- STAR WARS Jedi: Fallen Order™
- The Outer Worlds

This list does not immediately suggest an issue. For all the potentially distinct qualities of these specific games and their captures listed below, I have examples of other games and captures with the same qualities that are visible to the API.
- Similar age, expiration dates, and capture dates
- Special characters (or no special characters) in their titles
- Quality, including basic 1080p all the way up to 4K HDR

**Comment by jdaymude** [comment]
As of August 31, 2021, I have confirmed that this is not an issue with xbox2local, as a manual scan of the HTTP output does not contain any entries for these "invisible" games.

Moreover, it does not seem to be specific to [X API](https://xapi.us/), the third-party API that this project uses. I have also tried [OpenXBL](https://xbl.io/)'s `/dvr/screenshots` and `/dvr/gameclips` endpoints, but they return the same results. So this may be an issue with the way Microsoft serves up those results.

**Comment by KarineValenca** [comment]
Hello @jdaymude, did you find the solution to this problem? I'm having the same issue, including the games FIFA21 and Halo Infinite. I was checking this solution https://gamerdvr.com/gamer/waterishberet49/videos, and they are able to list all the clips correctly, but I don't want to use a private API.

**Comment by jdaymude** [comment]
Hi @KarineValenca, thanks for using xbox2local! I haven't been able to figure this out, unfortunately. Referencing my above comment on August 31, 2021, it seems that the problem is upstream, possibly with Microsoft. xbox2local isn't missing anything in the raw HTTP output, and the two public APIs I've tested ([X API](https://xapi.us/) and [OpenXBL](https://xbl.io/)) both miss the same "invisible" games. I'm not sure who to follow up with about this, but it certainly is annoying.

**Comment by KarineValenca** [comment]
I spent all day investigating this problem. I found this website + opensource API that is able to list all games:
- https://www.xboxreplay.net/
- https://github.com/XboxReplay/xboxlive-auth

After checking the code, I didn't find anything different I'm doing now, so I think the issue might be in the configuration of the Microsoft account. I'll update here if I find something :)
